package dev.harshit.traini8.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@MappedSuperclass
public class BaseModel {

    /**
     * Class serves as a base model for entities, providing common attributes
     * such as an autogenerated ID(Primary key for the entity) and
     * a creation timestamp stored as Epoch time in milliseconds.
     */


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Long createdOn;     // Store as Epoch time in milliseconds
}
